apiVersion: v1
kind: Service
metadata:
        name: back-end
spec:
        selector:
                app: back-end
        ports:
        - protocol: TCP
          port: 8181
          targetPort: 8181
        type: ClusterIP
